# Market Monitor Configuration
# File: monitor_config.yaml

thresholds:
  # Price movement thresholds
  price_breakout: 0.01  # 1% breakout threshold
  price_change_alert: 0.05  # 5% price change alert

  # Volume thresholds
  volume_spike: 2.0  # 2x average volume
  volume_drop: 0.5   # 50% of average volume

  # Volatility thresholds
  high_volatility: 0.5  # 50% annualized volatility
  volatility_spike: 1.5  # 1.5x average volatility

  # Technical indicators
  rsi_overbought: 70
  rsi_oversold: 30

indicators:
  - rsi
  - macd
  - bollinger_bands
  - moving_averages
  - volume_profile

risk_limits:
  max_drawdown: 0.20  # 20% maximum drawdown
  max_position_size: 0.30  # 30% max position
  max_correlation: 0.80  # 80% correlation threshold
  max_leverage: 2.0  # 2x maximum leverage
  var_limit: 0.05  # 5% VaR limit

alert_settings:
  min_priority: 2  # Minimum priority level (1-4)
  max_alerts_per_symbol: 5
  alert_cooldown_minutes: 60

notification_channels:
  - console
  - file
  - webhook

monitoring_intervals:
  real_time: 1  # minutes
  standard: 5
  slow: 60
