"""
NCOS v11.6 - Base Strategy
Foundation for all trading strategies
"""
from typing import Dict, Any, List, Optional, Tuple
import asyncio
from datetime import datetime, timedelta
from abc import ABC, abstractmethod
from ..core.base import BaseComponent, logger

class StrategySignal:
    """Trading signal generated by strategy"""

    def __init__(self, signal_type: str, symbol: str, action: str, confidence: float):
        self.signal_type = signal_type  # 'entry', 'exit', 'modify'
        self.symbol = symbol
        self.action = action  # 'BUY', 'SELL', 'CLOSE'
        self.confidence = confidence  # 0.0 to 1.0
        self.timestamp = datetime.now()
