    # .streamlit/secrets.toml
    finnhub_api_key = "d1fiar1r01qig3h21l20d1fiar1r01qig3h21l2g"
    newsapi_key = "713b3bd82121482aaa0ecdc9af77b6da"
    trading_economics_api_key = "1750867cdfc34c6:288nxdz64y932qq"
    fred_api_key = "6a980b8c2421503564570ecf4d765173"
    openai_API = "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"
    OPENAI_API_KEY = "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"
    data_directory = "/Users/tom/Documents/_trade/_exports/_tick/parquet/"
    raw_data_directory = "/Users/tom/Documents/_trade/_exports/_tick/_raw"
    JSONdir = "/Users/tom/Documents/_trade/_exports/_tick/midas_analysis/json"
    bar_data_directory = "/Users/tom/Documents/_trade/_exports/_tick/_bars"
    data_path = "/Users/tom/Documents/_trade/_exports/_tick"
    BAR_DATA_DIR = "/Users/tom/Documents/_trade/_exports/_tick/_bars"
    PARQUET_DATA_DIR = "/Users/tom/Documents/_trade/_exports/_tick/parquet/"
    raw_data = "/Users/tom/Documents/_trade/_exports/_tick"
    enriched_data = "/Users/tom/Documents/_trade/_exports/_tick/parquet"
    tick_data = "/Users/tom/Documents/_trade/_exports/_tick/_raw"
    tick_data_enriched = "/Users/tom/Documents/_trade/_exports/_tick/parquet/parquet"

[folders]
    data_directory = "/Users/tom/Documents/_trade/_exports/_tick/parquet/"
    raw_data_directory = "/Users/tom/Documents/_trade/_exports/_tick/_raw"
    JSONdir = "/Users/tom/Documents/_trade/_exports/_tick/midas_analysis"
    bar_data_directory = "/Users/tom/Documents/_trade/_exports/_tick/_bars"
    data_path = "/Users/tom/Documents/_trade/_exports/_tick"
    BAR_DATA_DIR = "/Users/tom/Documents/_trade/_exports/_tick/_bars"
    PARQUET_DATA_DIR = "/Users/tom/Documents/_trade/_exports/_tick/parquet"
    raw_data = "/Users/tom/Documents/_trade/_exports/_tick"
    enriched_data = "/Users/tom/Documents/_trade/_exports/_tick/parquet" 
    tick_data = "/Users/tom/Documents/_trade/_exports/_tick/_raw"
    tick_data_enriched = "/Users/tom/Documents/_trade/_exports/_tick/parquet/parquet"
   